default_language_version:
    python: python3.10
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-ast
        - id: check-case-conflict
        - id: check-yaml

  - repo: local
    hooks:
    - id: autopep8
      name: autopep8
      entry: poetry run autopep8
      args: [-d]
      language: system
      types: [ python ]

    - id: isort
      name: isort
      args: [--settings-path=pyproject.toml]
      entry: poetry run isort
      language: system
      types: [ python ]

    - id: flake8
      name: flake8
      args: [--config=pyproject.toml]
      entry: poetry run flake8
      language: system
      types: [ python ]
